<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>redb.Route.Redis</PackageId>
    <Description>Redis transport for redb.Route ESB framework.</Description>
    <PackageTags>esb;messaging;redis;redb</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="redb.Route.Tests.Redis" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\redb.Route\redb.Route.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.11.8" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>