<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\redb.Route\redb.Route.csproj" />
    <ProjectReference Include="..\..\redb.Route.GenericFile\redb.Route.GenericFile.csproj" />
    <ProjectReference Include="..\..\redb.Route.Ftp\redb.Route.Ftp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentFTP" Version="54.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
  </ItemGroup>

</Project>

