<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\redb.Route\redb.Route.csproj" />
    <ProjectReference Include="..\..\redb.Route.Kafka\redb.Route.Kafka.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.Kafka" Version="4.3.0" />
  </ItemGroup>

</Project>

