using System.Text;
using System.Xml.Linq;
using Microsoft.Extensions.DependencyInjection;
using redb.Route.Abstractions;
using redb.Route.Components.Bean;
using redb.Route.Core;

namespace redb.Route.Xml;

/// <summary>
/// The Ф6 generator: a <c>.route.xml</c> document printed as the fluent C# it parses into — the
/// same traversal as the loader with a different receiver, each element printed by its own
/// contribution (the Р21 print face), so the parser and the generator cannot drift apart.
/// Readable style is for a human migrating off XML (descriptions become comments); machine style
/// adds <c>#line</c> directives so diagnostics point back at the XML. The honesty check is
/// mechanical: load the XML, run the generated <c>Configure</c>, and compare the two trees with
/// <c>RouteDescriber</c> — the tests do exactly that for every shipped example.
/// </summary>
public static class XmlCodeGenerator
{
    /// <summary>Generates one RouteBuilder class from a route document.</summary>
    /// <param name="document">The parsed document (with line info for machine style).</param>
    /// <param name="className">The class name (derive from the file name: orders → OrdersRoutes).</param>
    /// <param name="ns">The namespace of the generated class.</param>
    /// <param name="style">Readable for migration, machine for a build step.</param>
    /// <param name="sourceName">The XML path — printed in the header and #line directives.</param>
    /// <param name="options">Loader options carrying package contributions, if any.</param>
    public static string Generate(
        XDocument document,
        string className,
        string ns,
        CodeGenStyle style = CodeGenStyle.Readable,
        string sourceName = "<inline>",
        XmlRouteLoaderOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentException.ThrowIfNullOrWhiteSpace(className);
        ArgumentException.ThrowIfNullOrWhiteSpace(ns);
        var root = document.Root;
        if (root is null || root.Name.LocalName != "routes" || root.Name.NamespaceName != XmlRouteLoader.Namespace)
            throw new InvalidOperationException(
                $"the generator reads <routes xmlns=\"{XmlRouteLoader.Namespace}\"> documents.");

        var registry = ElementRegistry.CreateDefault(options?.Extensions);
        var resourceRoot = sourceName != "<inline>" ? Path.GetDirectoryName(Path.GetFullPath(sourceName)) : null;
        var writer = new XmlCodeWriter(registry, style, sourceName, resourceRoot);

        writer.Line($"// <auto-generated from {sourceName.Replace('\\', '/')} — do not edit; regenerate instead. />");
        writer.Line("#nullable enable");
        writer.Line("using System;");
        writer.Line("using System.Collections.Generic;");
        writer.Line("using Microsoft.Extensions.Logging;");
        writer.Line("using redb.Route.Abstractions;");
        writer.Line("using redb.Route.Aggregation;");
        writer.Line("using redb.Route.ControlBus;");
        writer.Line("using redb.Route.Core;");
        writer.Line("using redb.Route.Transactions;");
        writer.Line("using redb.Route.Xml;");
        writer.Line("using redb.Route.Xslt;");
        // Namespaces the registered package printers ask for (GeneratedUsings face).
        foreach (var extra in (options?.Extensions ?? [])
                     .SelectMany(c => c.GeneratedUsings).Distinct().Order(StringComparer.Ordinal))
            writer.Line($"using {extra};");
        writer.BlankLine();
        writer.Line($"namespace {ns};");
        writer.BlankLine();
        writer.Line("/// <summary>A generated route builder — see the header for the source file.</summary>");
        writer.Line($"public sealed class {className} : RouteBuilder");
        writer.Line("{");
        writer.Indent();
        writer.Line("protected override void Configure()");
        writer.Line("{");
        writer.Indent();

        // Section order mirrors the loader: beans, container handlers, routes.
        foreach (var bean in root.Elements().Where(e => e.Name.LocalName == "bean"))
            PrintBean(bean, writer);

        foreach (var handler in root.Elements().Where(e => e.Name.LocalName
                     is "onException" or "intercept" or "interceptFrom" or "interceptSendToEndpoint" or "onCompletion"))
            PrintContainerHandler(handler, writer);

        foreach (var element in root.Elements())
        {
            if (registry.Find(element.Name.LocalName) is { Kind: XmlElementKind.TopLevel } topLevel)
                topLevel.Print(element, writer);
        }

        foreach (var route in root.Elements().Where(e => e.Name.LocalName == "route"))
            PrintRoute(route, writer);

        writer.Outdent();
        writer.Line("}");
        writer.Outdent();
        writer.Line("}");
        if (style == CodeGenStyle.Machine)
            writer.Line("#line default");
        return writer.Text;
    }

    private static void PrintBean(XElement bean, XmlCodeWriter writer)
    {
        var name = bean.Attribute("name")?.Value ?? "";
        writer.MapTo(bean);
        writer.Line($"Context!.AddToRegistry({XmlCodeWriter.Str(name)}, {BeanExpression(bean)});");
    }

    /// <summary>A bean as a <c>XmlBeans.Create(...)</c> expression; nested anonymous beans recurse.</summary>
    private static string BeanExpression(XElement bean)
    {
        var args = new StringBuilder();
        args.Append("XmlBeans.Create(Context!, ").Append(XmlCodeWriter.Str(bean.Attribute("type")?.Value ?? ""));
        var ctorArgs = bean.Elements().Where(e => e.Name.LocalName == "constructorArg")
            .Select(a => a.Elements().FirstOrDefault(c => c.Name.LocalName == "bean") is { } nested
                ? BeanExpression(nested)
                : XmlCodeWriter.Str(a.Attribute("value")?.Value ?? ""));
        args.Append(", [").Append(string.Join(", ", ctorArgs)).Append(']');
        var properties = bean.Elements().Where(e => e.Name.LocalName == "property")
            .Select(p => p.Elements().FirstOrDefault(c => c.Name.LocalName == "bean") is { } nestedValue
                ? $"({XmlCodeWriter.Str(p.Attribute("key")?.Value ?? "")}, {BeanExpression(nestedValue)})"
                : $"({XmlCodeWriter.Str(p.Attribute("key")?.Value ?? "")}, {XmlCodeWriter.Str(p.Attribute("value")?.Value ?? "")})");
        args.Append(", [").Append(string.Join(", ", properties)).Append(']');
        if (bean.Attribute("factoryMethod")?.Value is { Length: > 0 } factoryMethod)
            args.Append(", ").Append(XmlCodeWriter.Str(factoryMethod));
        return args.Append(')').ToString();
    }

    private static void PrintContainerHandler(XElement handler, XmlCodeWriter writer)
    {
        // Builder-level: the same shapes as the route level, statements on a fresh variable,
        // no End call (a builder-level definition has no parent to return to).
        switch (handler.Name.LocalName)
        {
            case "onException":
            {
                var types = (handler.Attribute("exceptions")?.Value ?? "")
                    .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
                writer.PushRoot($"OnException({string.Join(", ", types.Select(XmlCodeWriter.TypeRef))})", handler, "handler");
                if (handler.Attribute("description")?.Value is { Length: > 0 } description)
                    writer.Config($"Description({XmlCodeWriter.Str(description)})");
                CoreElements.CoreContributions.PrintOnExceptionConfig(handler, writer);
                writer.PrintSteps(handler);
                writer.PopReceiver();
                break;
            }
            case "intercept":
            case "interceptFrom":
            case "interceptSendToEndpoint":
            {
                var verb = char.ToUpperInvariant(handler.Name.LocalName[0]) + handler.Name.LocalName[1..];
                var arg = handler.Attribute("uri")?.Value is { } uri ? XmlCodeWriter.Str(uri) : "";
                writer.PushRoot($"{verb}({arg})", handler, "handler");
                if (handler.Attribute("skipSendToOriginalEndpoint")?.Value == "true")
                    writer.Config("SkipSendToOriginalEndpoint()");
                CoreElements.CoreContributions.PrintWhenConditionThenSteps(handler, writer);
                writer.PopReceiver();
                break;
            }
            default:
            {
                writer.PushRoot("OnCompletion()", handler, "handler");
                if (handler.Attribute("onCompleteOnly")?.Value == "true") writer.Config("OnCompleteOnly()");
                if (handler.Attribute("onFailureOnly")?.Value == "true") writer.Config("OnFailureOnly()");
                if (handler.Attribute("modeBeforeConsumer")?.Value == "true") writer.Config("ModeBeforeConsumer()");
                CoreElements.CoreContributions.PrintWhenConditionThenSteps(handler, writer);
                writer.PopReceiver();
                break;
            }
        }
    }

    private static void PrintRoute(XElement route, XmlCodeWriter writer)
    {
        // enabled= is a load-time decision from live configuration; generated code has no
        // configuration at generation time, so the attribute is refused rather than mistranslated.
        if (route.Attribute("enabled") is { } enabled)
        {
            if (bool.TryParse(enabled.Value, out var isEnabled))
            {
                if (!isEnabled)
                    return;
            }
            else
            {
                throw new NotSupportedException(
                    $"route '{route.Attribute("id")?.Value}': enabled=\"{enabled.Value}\" resolves from configuration " +
                    "at load time — decide it before generating, or keep this route in XML.");
            }
        }

        writer.BlankLine();
        if (writer.Style == CodeGenStyle.Readable && route.Attribute("description")?.Value is { Length: > 0 } comment)
            writer.Line($"// {comment}");

        var from = route.Elements().First(e => e.Name.LocalName == "from");
        var fromUri = from.Attribute("uri")?.Value is { } uri
            ? XmlCodeWriter.Str(uri)
            : XmlCodeWriter.Str(StructuredEndpoint.NormalizeForPrint(from.Elements().First()));
        writer.PushRoot($"From({fromUri})", route, "route");
        if (route.Attribute("id")?.Value is { Length: > 0 } id)
            writer.Config($"RouteId({XmlCodeWriter.Str(id)})");
        if (route.Attribute("description")?.Value is { Length: > 0 } description)
            writer.Config($"Description({XmlCodeWriter.Str(description)})");
        if (route.Attribute("autoStart")?.Value is { } autoStart)
            writer.Config($"AutoStart({XmlCodeWriter.Bool(bool.Parse(autoStart))})");
        if (route.Attribute("cluster")?.Value is { } cluster)
            writer.Config($"Cluster({XmlCodeWriter.Bool(bool.Parse(cluster))})");
        if (route.Attribute("messageHistory")?.Value is { } history)
            writer.Config($"MessageHistory({XmlCodeWriter.Bool(bool.Parse(history))})");
        if (route.Attribute("processingTimeout")?.Value is { } timeout)
            writer.Config($"ProcessingTimeout({XmlCodeWriter.Ts(TimeSpan.Parse(timeout, System.Globalization.CultureInfo.InvariantCulture))})");
        if (route.Attribute("routePolicy")?.Value is { Length: > 0 } policy)
            writer.Config($"RoutePolicy({XmlCodeWriter.Str(policy)})");

        foreach (var step in route.Elements().Where(e => e.Name.LocalName != "from"))
            writer.PrintStep(step);

        writer.PopReceiver();
    }
}

/// <summary>
/// The runtime half of generated bean registrations: builds an instance the same way the
/// <c>&lt;bean&gt;</c> section does — the registered <c>IBeanTypeResolver</c> decides what the
/// type name means, constructor args and property values bind through the shared converter.
/// </summary>
public static class XmlBeans
{
    /// <summary>
    /// Creates a bean instance for a generated registration. A property value is either a string,
    /// converted to the property type the way a URI option is, or an object built by a nested
    /// anonymous bean and assigned as it is. <paramref name="factoryMethod"/> names a public static
    /// creator to call instead of a constructor, with the constructor arguments as its parameters.
    /// </summary>
    public static object Create(
        IRouteContext context,
        string typeName,
        object?[] constructorArgs,
        (string Key, object? Value)[] properties,
        string? factoryMethod = null)
    {
        ArgumentNullException.ThrowIfNull(context);
        var resolver = context.GetService<IBeanTypeResolver>() ?? DefaultBeanTypeResolver.Instance;
        var type = resolver.Resolve(typeName)
            ?? throw new InvalidOperationException($"bean type '{typeName}' was not found in the loaded assemblies.");
        var provider = context.GetServiceProvider();
        object instance;
        if (!string.IsNullOrEmpty(factoryMethod))
        {
            var method = type.GetMethods(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static)
                .FirstOrDefault(m => m.Name == factoryMethod && m.GetParameters().Length == constructorArgs.Length)
                ?? throw new InvalidOperationException(
                    $"type '{type.FullName}' has no public static method '{factoryMethod}' taking {constructorArgs.Length} argument(s).");
            var parameters = method.GetParameters();
            var bound = new object?[parameters.Length];
            for (var i = 0; i < parameters.Length; i++)
                bound[i] = constructorArgs[i] is string text && parameters[i].ParameterType != typeof(string)
                    ? OptionValueConverter.Convert(text, parameters[i].ParameterType)
                    : constructorArgs[i];
            instance = method.Invoke(null, bound)
                ?? throw new InvalidOperationException($"'{type.FullName}.{factoryMethod}' returned null.");
        }
        else
        {
            instance = constructorArgs.Length > 0
                ? ActivatorUtilities.CreateInstance(provider ?? EmptyProvider.Instance, type, constructorArgs!)
                : ActivatorUtilities.CreateInstance(provider ?? EmptyProvider.Instance, type);
        }
        foreach (var (key, value) in properties)
        {
            var property = type.GetProperty(key)
                ?? throw new InvalidOperationException($"type '{type.FullName}' has no property '{key}'.");
            if (value is not string text)
            {
                if (value is not null && !property.PropertyType.IsInstanceOfType(value))
                    throw new InvalidOperationException(
                        $"'{value.GetType().FullName}' is not assignable to {property.PropertyType.Name} for '{key}'.");
                property.SetValue(instance, value);
                continue;
            }
            var resolved = context is RouteContext live ? live.ResolvePlaceholders(text) : text;
            var converted = OptionValueConverter.Convert(resolved, property.PropertyType)
                ?? throw new InvalidOperationException($"'{resolved}' is not convertible to {property.PropertyType.Name} for '{key}'.");
            property.SetValue(instance, converted);
        }
        return instance;
    }

    private sealed class EmptyProvider : IServiceProvider
    {
        public static readonly EmptyProvider Instance = new();
        public object? GetService(Type serviceType) => null;
    }
}
