using redb.Route.Core;
using redb.Route.RabbitMQ;

namespace redb.Route.Tests.RabbitMQ;

public sealed class RabbitMQComponentTests
{
    private readonly RabbitMQComponent _sut = new();

    [Fact]
    public void Scheme_ReturnsRabbitMQ()
    {
        _sut.Scheme.Should().Be("rabbitmq");
    }

    [Fact]
    public void CreateEndpoint_ValidUri_ReturnsRabbitMQEndpoint()
    {
        var uri = EndpointUriParser.Parse("rabbitmq://my-queue?host=localhost");

        var endpoint = _sut.CreateEndpoint(uri);

        endpoint.Should().BeOfType<RabbitMQEndpoint>();
        var rmq = (RabbitMQEndpoint)endpoint;
        rmq.QueueName.Should().Be("my-queue");
    }

    [Fact]
    public void CreateEndpoint_NullUri_Throws()
    {
        var act = () => _sut.CreateEndpoint(null!);
        act.Should().Throw<ArgumentNullException>();
    }

    [Fact]
    public void CreateEndpoint_WithExchangeAndRouting_ParsesCorrectly()
    {
        var uri = EndpointUriParser.Parse(
            "rabbitmq://orders?host=rabbit:5672&exchange=ex1&exchangeType=topic&routingKey=order.*&durable=true&declare=true");

        var endpoint = (RabbitMQEndpoint)_sut.CreateEndpoint(uri);

        endpoint.QueueName.Should().Be("orders");
    }

    [Fact]
    public void CreateEndpoint_WithConsumerOptions_ParsesCorrectly()
    {
        var uri = EndpointUriParser.Parse(
            "rabbitmq://q1?host=localhost&concurrentConsumers=4&prefetchCount=20&transacted=true");

        var endpoint = (RabbitMQEndpoint)_sut.CreateEndpoint(uri);
        endpoint.QueueName.Should().Be("q1");
    }

    [Fact]
    public void CreateEndpoint_WithRpcOptions_ParsesCorrectly()
    {
        var uri = EndpointUriParser.Parse("rabbitmq://rpc-queue?host=localhost&replyTo=true&timeout=30");
        var endpoint = (RabbitMQEndpoint)_sut.CreateEndpoint(uri);
        endpoint.QueueName.Should().Be("rpc-queue");
    }

    [Fact]
    public void CreateEndpoint_EmptyQueue_AllowsAutoGenerated()
    {
        // Empty path → auto-generated exclusive queue (valid scenario)
        var uri = EndpointUriParser.Parse("rabbitmq://?host=localhost&exchange=my-exchange");
        var endpoint = (RabbitMQEndpoint)_sut.CreateEndpoint(uri);
        endpoint.QueueName.Should().BeEmpty();
    }
}
