<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\redb.Route\redb.Route.csproj" />
    <ProjectReference Include="..\..\redb.Route.RabbitMQ\redb.Route.RabbitMQ.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.RabbitMq" Version="4.3.0" />
  </ItemGroup>

</Project>

