<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="SerialNumberRequest">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="RequestId">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="1" />
              <xs:maxLength value="64" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="Gtin">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[0-9]{14}" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="Quantity" type="xs:positiveInteger" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>
