<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>redb.Route.RabbitMQ</PackageId>
    <Description>RabbitMQ transport for redb.Route ESB framework.</Description>
    <PackageTags>esb;messaging;rabbitmq;redb</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="redb.Route.Tests.RabbitMQ" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\redb.Route\redb.Route.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>