<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\redb.Route\redb.Route.csproj" />
    <ProjectReference Include="..\..\src\redb.Route.Llm\redb.Route.Llm.csproj" />
    <ProjectReference Include="..\..\src\redb.Route.Llm.Abstractions\redb.Route.Llm.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\redb.Route.Llm.Mcp\redb.Route.Llm.Mcp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
