<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\redb.Route\redb.Route.csproj" />
    <ProjectReference Include="..\..\redb.Route.Sqs\redb.Route.Sqs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
  </ItemGroup>

</Project>

